source/InjectHooksMain.cpp
source/game_sa/CRGBA.h
source/game_sa/CShinyTexts.cpp
source/game_sa/CShinyTexts.h

Tested, works perfectly.
Here it is:

CShinyTexts

---

source/InjectHooksMain.cpp
source/game_sa/CBulletTrace.h
source/game_sa/CBulletTraces.cpp
source/game_sa/CBulletTraces.h

CBulletTraces

---

source/game_sa/CDraw.cpp
source/game_sa/CRadar.cpp
source/game_sa/CTxdStore.cpp
source/game_sa/CWorld.cpp
source/game_sa/Events/CEventAcquaintancePed.cpp
source/game_sa/Events/CEventAttractor.cpp
source/game_sa/Events/CEventEditableResponse.cpp
source/game_sa/Tasks/CScriptedBrainTaskStore.cpp

Fixes d64a3f61e890289b6c692a5626ff1cda09e72dfb

Fix hooks installed with incorrect identifier

---

source/game_sa/CExplosion.cpp
source/game_sa/CExplosion.h
source/game_sa/Entity/Vehicle/CAutomobile.cpp

Fix explosions

---

source/game_sa/Fx/Fx_c.cpp
source/game_sa/Fx/Fx_c.h

* InitStaticSystems
* ExitStaticSystems
* InitEntitySystems
* Init
* Exit
* Reset
* Render
* SetFxQuality
* GetFxQuality

Reverse 9 Fx_c funcs

---

source/InjectHooksMain.cpp
source/game_sa/Fx/Fx_c.cpp
source/game_sa/Fx/Fx_c.h

Used for particle effects.
Go out on groove street and shoot the boxes (right against CJs house)

RenderAddTri, RenderEnd, RenderBegin

---

CMakeLists.txt
premake5.lua
source/game_sa/CRenderer.cpp
source/toolsmenu/CDebugMenu.cpp
source/toolsmenu/CDebugMenu.h
source/toolsmenu/DebugModules/Collision/Collision.cpp
source/toolsmenu/DebugModules/Collision/Collision.h

Activate: ``F7`` -> ``Rendering`` -> ``Collision``

[debug] Draw Collision

---

source/game_sa/Collision/ColAccel.cpp
source/game_sa/Collision/ColAccel.h
source/game_sa/Collision/ColModel.cpp
source/game_sa/Collision/ColModel.h
source/game_sa/Collision/ColSphere.cpp
source/game_sa/Collision/ColSphere.h
source/game_sa/Collision/ColStore.cpp
source/game_sa/Collision/Sphere.cpp
source/game_sa/Entity/Object/Object.cpp
source/game_sa/FileLoader.cpp
source/game_sa/Models/PedModelInfo.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleClimb.cpp

`CColModel::m_boundSphere` was incorrectly `CColSphere` instead of `CSphere`.
Sadly the game crashes instantly now..

Fix CColModel::m_boundSphere type (Change from CColsphere to CSphere)

---

source/game_sa/Renderer.cpp

Unhook ScanBigBuildingList by default, and add some asserts

---

source/game_sa/Entity/Physical.cpp

Triggered run-time check, so we got to init it before usage.

Fix uninitalized variable used

---

source/game_sa/Radar.cpp

Fixes #90
(Test before merging)

Fix blip scaling in radar

---

source/game_sa/PlayerInfo.h

Accidentally copying it will cause a crash

Delete copy/move ctors of PlayerInfo

---

source/game_sa/Radar.cpp

Use floor in CRadar::DrawSprite 

---

source/toolsmenu/CDebugMenu.cpp
source/toolsmenu/DebugModules/Cheat/CheatDebugModule.cpp

Adds godmode cheat (Simple checkbox in Cheat menu)

Add godmode cheat

---

source/game_sa/MenuSystem.cpp
source/game_sa/MenuSystem.h
source/game_sa/Stats.cpp
source/game_sa/Stats.h

(diffs on if-statements are caused by clang-format)

Fix FindMaxNumberOfGroupMembers

---

source/game_sa/Entity/Entity.cpp
source/game_sa/Garage.cpp
source/game_sa/Garage.h
source/game_sa/Pools.cpp
source/game_sa/Pools.h

Game crashes while garage closes. Reversed `StoreAndRemoveCarsForThisHideOut` to fix, similar to `FindMaxNumberOfGroupMembers` crash

Fix garage crash

---

source/reversiblehooks/ReversibleHooks.h
source/toolsmenu/CDebugMenu.cpp
source/toolsmenu/CDebugMenu.h
source/toolsmenu/HooksDebugModule.cpp
source/toolsmenu/HooksDebugModule.h
source/toolsmenu/TristateCheckbox.h

- It includes fixes for the incorrect collision asserts - Which I'm going to remove shortly (and open a seprate PR)
- Move it to a separate module
- This PR will have a follow-up adding categories (and fixing the todo in the code)
- New, improved style using tri-state checkboxes:

Re-style and refactor hook tools debug module

---

source/game_sa/Entity/Ped/Ped.cpp
source/game_sa/Entity/Ped/Ped.h
source/game_sa/Entity/Vehicle/Vehicle.cpp
source/game_sa/Entity/Vehicle/Vehicle.h
source/game_sa/PedGroup.h
source/game_sa/PedGroupMembership.cpp
source/game_sa/PedGroupMembership.h
source/game_sa/World.cpp
source/game_sa/World.h

Not sure if `ExcitingStuffInArea` was fixed. @yukani will test it, right?
Possibly fixes #110 and #109
Tested: Fixes both issues

Fix ExcitingStuffInArea and SprayPaintWorld (Closes #110, #109)

---

source/game_sa/WaterCannon.cpp
source/game_sa/WaterCannon.h
source/toolsmenu/DebugModules/CTeleportDebugModule.cpp

Fix watercannon issue from #89 
Also fixes small bug in the teleporter module (I can't bother to open a PR for it)

Fix watercannons

---

source/extensions/enumerate.hpp

Add `enumerate` function

---

.github/workflows/build.yml

Fix wrong artifacts

---

source/game_sa/Font.cpp

Fix CFont::GetStringWidth

---

source/game_sa/Entity/Physical.cpp

Fix matrix position component in CPhysical::PositionAttachedEntity()

---

source/toolsmenu/CDebugMenu.cpp
source/toolsmenu/DebugModules/FXDebugModule.cpp
source/toolsmenu/DebugModules/FXDebugModule.h

Migrate FX tool stuff into a separate module

---

source/game_sa/Entity/Object/Object.cpp

Fixes lack of collision in pool minigame
Fixes #142

fix CObject::SpecialEntityPreCollisionStuff

---

source/game_sa/Audio/AEStreamThread.cpp
source/game_sa/Audio/AEStreamThread.h
source/game_sa/OnscreenCounterEntry.cpp

Fixes #118 and onscreen counter overflow

Fix dancing/lowrider minigame

---

source/game_sa/PedIntelligence.cpp

Fix CPedIntelligence::FlushImmediately

---

source/Base.h
source/game_sa/Collision/ColBox.h
source/game_sa/Collision/ColHelpers.h
source/game_sa/Collision/ColSphere.h
source/game_sa/Collision/Collision.cpp
source/game_sa/Collision/Collision.h
source/game_sa/Collision/CollisionData.cpp
source/game_sa/Collision/CollisionData.h
source/game_sa/Core/Matrix.cpp
source/game_sa/Core/Matrix.h
source/game_sa/Entity/Physical.cpp
source/game_sa/FileLoader.cpp
source/game_sa/PedPlacement.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleClimb.cpp
source/game_sa/World.cpp
source/game_sa/World.h
source/toolsmenu/DebugModules/Collision/CollisionDebugModule.cpp

Unit tested, works like original. (Not necessarily looks like it)

ProcessColModels

---

source/game_sa/DamageManager.cpp
source/game_sa/DamageManager.h
source/reversiblehooks/ReversibleHooks.h

Fix CDamageManager::GetWheelStatus

---

source/game_sa/Renderer.cpp
source/game_sa/World.cpp

Signed-off-by: Pirulax <patrikjankovics7@gmail.com>

fix out of bounds array

---

source/game_sa/Core/Quaternion.cpp
source/game_sa/Core/Quaternion.h
source/game_sa/Entity/Physical.cpp

Hopefully fixes door going crazy when entering/exiting

Properly initialize vectors and quaternions in CPhysical constructor

---

source/game_sa/Entity/Entity.cpp
source/game_sa/Entity/Physical.cpp

- Fixed uninitialized variables in CPhysical
- Cleaned up cross vectors creation in CPhysical
- Fixed CEntity::PreRender skipping logic in some cases
Fixes #171 and probably a lot of small physics bugs

Fix some CPhysics bugs, fix CEntity::PreRender

---

source/game_sa/Entity/Entity.cpp
source/game_sa/Entity/Entity.h
source/game_sa/Entity/Physical.h
source/game_sa/EntryExit.h
source/game_sa/Enums/eAreaCodes.h
source/game_sa/FileLoader.cpp
source/game_sa/WaterCreature_c.cpp
source/toolsmenu/CDebugMenu.cpp
source/toolsmenu/DebugModules/CTeleportDebugModule.cpp
source/toolsmenu/DebugModules/CTeleportDebugModule.h

* teleport vehicles support
* added interior selection
* made finding ground z optional

Improve teleporter tool

---

source/reversiblehooks/HookCategory.h
source/reversiblehooks/ReversibleHook/Base.h
source/reversiblehooks/ReversibleHook/Simple.cpp
source/reversiblehooks/ReversibleHook/Simple.h
source/reversiblehooks/ReversibleHook/Virtual.cpp
source/reversiblehooks/ReversibleHooks.cpp
source/reversiblehooks/RootHookCategory.h
source/toolsmenu/DebugModules/CTeleportDebugModule.cpp
source/toolsmenu/DebugModules/HooksDebugModule.cpp
source/toolsmenu/Utility.h

- Sort function and categories by name
- Improve state change calculation performance
- Fix incorrect state propagation (caused category state to sometimes be incorrect)
- Open root, ~~and it's level 1 children~~ by default
- Show all items when search tool is active
Closes #99 
[Help with search tool's usage.](https://github.com/Updated-Classic/gta-reversed-modern/discussions/190)

Hooks tool improvements

---

source/game_sa/WaterLevel.cpp
source/game_sa/WaterLevel.h

Adds stubs for some known functions.
There's a lot that we don't know the PC addresses of, but it's fine, as those functions probably aren't used outside CWaterLevel.
Ran the game it worked fine. So it can be merged.

CWaterLevel stubs

---

source/InjectHooksMain.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexFollowLeaderInFormation.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexFollowLeaderInFormation.h

Not used anywhere yet, so it can be merged right away

CTaskComplexFollowLeaderInFormation stub

---

source/game_sa/Core/Pool.h

Added it because it seemed like task pool is getting full.. and that was the case!
Tested it briefly, works fine, can be merged after CI passes

Shit the pool full of asserts

---

source/game_sa/Weather.cpp

Fixes #185
will look for 'fixme' funcs too if they're problematic.

Fix CWeather::SetWeatherToAppropriateTypeNow

---

source/game_sa/Entity/Ped/PlayerPed.cpp

**bug found**, breath on the ground is not restored
Add code from ida database

Fix for infinite breath increase in water

---

source/game_sa/Font.cpp
source/game_sa/Font.h

non-english text aligment menu fix
Please Check
[67a8f0e](https://github.com/Updated-Classic/gta-reversed-modern/commit/67a8f0eda9dc243394bb342cb2116f6f93241335)

CFont::FindSubFontCharacter

---

source/InjectHooksMain.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexTurnToFaceEntityOrCoord.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexTurnToFaceEntityOrCoord.h

Game launched, no crash.
Should be good.

CTaskComplexTurnToFaceEntityOrCoord

---

source/InjectHooksMain.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleBeHit.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleBeHit.h

`CTaskSimpleBeHit`

---

source/InjectHooksMain.cpp
source/app/platform/win/VideoMode.cpp
source/app/platform/win/VideoMode.h
source/game_sa/Frontend/MenuManager_Process.cpp
source/game_sa/GxtChar.cpp

Fix resolution change logic, actually inject VideoMode hooks

---

source/game_sa/Audio/entities/AEVehicleAudioEntity.cpp
source/game_sa/CarCtrl.cpp

Fix police chase roadblocks causing crash, fix random crash in Audio engine

---

source/InjectHooksMain.cpp
source/game_sa/Entity/Entity.cpp
source/game_sa/Entity/Entity.h
source/game_sa/Tasks/TaskTypes/TaskComplexTrackEntity.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexTrackEntity.h

Couldn't, because I'm not really sure how to trigger the task to be created.
It's only called from one place.

`CTaskComplexTrackEntity`

---

source/InjectHooksMain.cpp
source/game_sa/Enums/eTargetDoor.h
source/game_sa/Tasks/TaskTypes/TaskComplexCarDrive.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexEnterAnyCarAsDriver.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleCarGetIn.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleCarGetIn.h
source/reversiblehooks/ReversibleHooks.h

`CTaskSimpleCarGetIn`

---

source/game_sa/Entity/Vehicle/Automobile.cpp

Fixes #363, didn't try the mission but I've bought hydraulics and could control it without issues

Fix CAutomobile::HydraulicControl() logic

---

source/game_sa/CullZones.cpp
source/game_sa/CullZones.h

Reversed FewerCars

---

source/game_sa/Camera.cpp
source/game_sa/Core/QuadTreeNode.cpp
source/game_sa/Core/QuadTreeNode.h
source/game_sa/Core/Rect.cpp
source/game_sa/Core/Rect.h
source/game_sa/Entity/Entity.cpp
source/game_sa/Entity/Physical.cpp
source/game_sa/Font.cpp
source/game_sa/Frontend/MenuManager_Draw.cpp
source/game_sa/Hud.cpp
source/game_sa/MenuSystem.cpp
source/game_sa/Radar.cpp
source/game_sa/Sprite2d.cpp

Finally fix this shit after 10+ years lol

Fix CRect field names

---

source/game_sa/Entity/Vehicle/Bike.cpp
source/game_sa/Entity/Vehicle/QuadBike.cpp
source/game_sa/Entity/Vehicle/QuadBike.h
source/game_sa/RideAnimData.h
source/game_sa/cHandlingDataMgr.h

We should probably add an enum for handling IDs.

Fix quadbike incorrect handling data used

---

source/game_sa/Entity/Vehicle/Automobile.cpp
source/game_sa/Entity/Vehicle/Automobile.h
source/game_sa/Shopping.cpp

Fix a security issue at CShopping::Buy

---

source/game_sa/Pipelines/CustomCarEnvMap/CustomCarEnvMapPipeline.cpp

I'm still really unsure how that flag member var works, but okay.

`CustomPipeMaterialSetup`

---

source/InjectHooksMain.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleSetCharDecisionMaker.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleSetCharDecisionMaker.h

Untested (game launches), but code is simple enough to be merged imho.

`CTaskSimpleSetCharDecisionMaker`

---

source/InjectHooksMain.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleCarOpenLockedDoorFromOutside.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleCarOpenLockedDoorFromOutside.h

Tested: Game launches, no crash.
Constructor not called,but given the code complexity, we can merge it.

`CTaskSimpleCarOpenLockedDoorFromOutside`

---

source/InjectHooksMain.cpp
source/app/app_debug.h
source/game_sa/Collision/ColSphere.h
source/game_sa/Tasks/TaskTypes/TaskComplexWalkRoundFire.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexWalkRoundFire.h
source/game_sa/Tasks/TaskTypes/TaskSimpleGoToPoint.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleGoToPoint.h

Tested, seemingly works?
It's triggered pretty randomly, so tbh I can't really test it that well.

`CTaskComplexWalkRoundFire`

---

source/InjectHooksMain.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleLookAbout.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleLookAbout.h

`CTaskSimpleLookAbout`

---

source/InjectHooksMain.cpp
source/game_sa/Core/Vector.cpp
source/game_sa/Core/Vector.h
source/game_sa/Core/Vector2D.h
source/game_sa/Entity/Vehicle/Vehicle.h
source/game_sa/PedGeometryAnalyser.h
source/game_sa/Tasks/TaskTypes/SeekEntity/TaskComplexSeekEntity.h
source/game_sa/Tasks/TaskTypes/TaskComplexAvoidEntity.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexAvoidEntity.h
source/game_sa/Tasks/TaskTypes/TaskComplexFollowPointRoute.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexFollowPointRoute.h
source/game_sa/Tasks/TaskTypes/TaskComplexGoToPointAndStandStill.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexGoToPointAndStandStill.h
source/game_sa/Tasks/TaskTypes/TaskComplexGoToPointAndStandStillAndAchieveHeading.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexGoToPointAndStandStillAndAchieveHeading.h
source/game_sa/Tasks/TaskTypes/TaskComplexGoToPointAndStandStillTimed.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexGoToPointAndStandStillTimed.h
source/game_sa/Tasks/TaskTypes/TaskComplexWalkRoundCar.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexWalkRoundCar.h
source/game_sa/Tasks/TaskTypes/TaskComplexWalkRoundFire.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleGoTo.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleGoTo.h
source/game_sa/Tasks/TaskTypes/TaskSimpleGoToPoint.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleGoToPoint.h
source/game_sa/Tasks/TaskTypes/TaskSimpleGoToPointFine.h
source/toolsmenu/CDebugMenu.cpp

Tested a little (entering a car uses this for example).
Also provided test code (in `CDebugMenu.cpp`, use with key `8` (not in the numpad))

`CTaskComplexFollowPointRoute`

---

source/InjectHooksMain.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleHitWall.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleHitWall.h

`CTaskSimpleHitWall`

---

source/InjectHooksMain.cpp
source/game_sa/Entity/Ped/Ped.cpp
source/game_sa/Entity/Ped/Ped.h
source/game_sa/PedIntelligence.h
source/game_sa/Tasks/Task.h
source/game_sa/Tasks/TaskTypes/TaskComplexRoadRage.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleDuck.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleDuck.h
source/game_sa/Tasks/TaskTypes/TaskSimpleGunControl.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleGunControl.h
source/game_sa/Tasks/TaskTypes/TaskSimplePlayerOnFoot.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleUseGun.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleUseGun.h

`CTaskSimpleGunControl`

---

source/InjectHooksMain.cpp
source/game_sa/Attractors/PedAttractor.h
source/game_sa/Scripts/Scripted2dEffects.cpp
source/game_sa/Scripts/Scripted2dEffects.h
source/game_sa/Tasks/TaskTypes/TaskComplexUseScriptedAttractor.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexUseScriptedAttractor.h

Untested (Not sure where to test it)
Game launches

`CTaskComplexUseScriptedAttractor`

---

source/InjectHooksMain.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexWaitForDryWeather.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexWaitForDryWeather.h

`CTaskComplexWaitForDryWeather`

---

source/InjectHooksMain.cpp
source/game_sa/Tasks/ScriptedBrainTaskStore.cpp
source/game_sa/Tasks/ScriptedBrainTaskStore.h
source/game_sa/Tasks/TaskTypes/TaskComplexUseScriptedBrain.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexUseScriptedBrain.h

Untested, because it doesn't seem to get triggered.
Game launches.

`CScriptedBrainTaskStore`

---

source/InjectHooksMain.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexWaitForBackup.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexWaitForBackup.h

Not used anywhere.
Game launches, so yeah...

`CTaskComplexWaitForBackup`

---

source/InjectHooksMain.cpp
source/game_sa/Tasks/TaskTypes/SeekEntity/PosCalculators/EntitySeekPosCalculatorXYOffset.h
source/game_sa/Tasks/TaskTypes/SeekEntity/TaskComplexSeekEntity.h
source/game_sa/Tasks/TaskTypes/SeekEntity/TaskComplexSeekEntityAnyMeans.h
source/game_sa/Tasks/TaskTypes/SeekEntity/TaskComplexSeekEntityAnyMeansXYOffset.cpp
source/game_sa/Tasks/TaskTypes/SeekEntity/TaskComplexSeekEntityAnyMeansXYOffset.h
source/game_sa/Tasks/TaskTypes/TaskComplexDriveToPoint.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexDriveToPoint.h

Game launches, that's all I know.
Can't test it for now.

`CTaskComplexSeekEntityAnyMeansXYOffset`

---

source/InjectHooksMain.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexFollowLeaderAnyMeans.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexFollowLeaderAnyMeans.h
source/game_sa/Tasks/TaskTypes/TaskComplexFollowLeaderInFormation.h

This one is seemingly unused.
There's one code path it might be called from, but it seems to be a dead "start" (eg.: the function's class that should create this task isn't ever constructed)

`CTaskComplexFollowLeaderAnyMeans`

---

source/game_sa/Tasks/Task.h
source/game_sa/Tasks/TaskTypes/TaskComplexPassObject.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexPassObject.h
source/game_sa/Tasks/TaskTypes/TaskSimpleHoldEntity.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleHoldEntity.h

I mean, game launches, I was lazy to wait it out to be triggered.
Might test later when #449 is merged

`CTaskComplexPassObject`

---

source/InjectHooksMain.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexCarDriveMission.h
source/game_sa/Tasks/TaskTypes/TaskComplexStealCar.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexStealCar.h
source/game_sa/Tasks/TaskTypes/TaskSimplePause.h
source/toolsmenu/CDebugMenu.cpp

Tested.
It is possible that `CTaskComplexCarDriveMissionFleeScene` has a bug, as it never ended, but this PR should be fine.

`CTaskComplexStealCar`

---

source/InjectHooksMain.cpp
source/game_sa/Population.cpp
source/game_sa/Population.h
source/game_sa/Tasks/TaskTypes/TaskComplexDie.h
source/game_sa/Tasks/TaskTypes/TaskComplexInWater.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexInWater.h
source/game_sa/Tasks/TaskTypes/TaskSimpleGunControl.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleRunAnim.h

`CTaskComplexInWater`

---

source/InjectHooksMain.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexLeaveCarAndFlee.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexLeaveCarAndFlee.h
source/toolsmenu/CDebugMenu.cpp

`CTaskComplexLeaveCarAndFlee`

---

source/InjectHooksMain.cpp
source/game_sa/ScriptsForBrains.cpp
source/game_sa/ScriptsForBrains.h
source/game_sa/Tasks/TaskTypes/TaskComplexSitDownThenIdleThenStandUp.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexSunbathe.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexSunbathe.h
source/game_sa/Tasks/TaskTypes/TaskComplexUseAttractor.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexUseAttractor.h
source/game_sa/Tasks/TaskTypes/TaskSimpleSitDown.cpp

Accidentally pushed to this repo, oh well.
Depends on #445

`TaskComplexUseAttractor`

---

source/InjectHooksMain.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexWanderFlee.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexWanderFlee.h

Game launches, no further tests needed imho.

`CTaskComplexWanderFlee`

---

source/game_sa/Entity/Vehicle/Vehicle.h
source/game_sa/Tasks/TaskTypes/TaskComplexScreamInCarThenLeave.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexScreamInCarThenLeave.h
source/toolsmenu/CDebugMenu.cpp

`CTaskComplexScreamInCarThenLeave`

---

source/InjectHooksMain.cpp
source/extensions/utility.hpp
source/game_sa/PedGroupMembership.h
source/game_sa/Tasks/TaskTypes/SeekEntity/PosCalculators/EntitySeekPosCalculatorRadiusAngleOffset.cpp
source/game_sa/Tasks/TaskTypes/SeekEntity/PosCalculators/EntitySeekPosCalculatorRadiusAngleOffset.h
source/game_sa/Tasks/TaskTypes/SeekEntity/TaskComplexSeekEntity.h
source/game_sa/Tasks/TaskTypes/TaskComplexSeekCoverUntilTargetDead.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexSeekCoverUntilTargetDead.h

Upon trying to test the task didn't really seem to get created or smth, not sure what was going on.
But it should work just fine I think

`CTaskComplexSeekCoverUntilTargetDead`

---

source/InjectHooksMain.cpp
source/extensions/utility.hpp
source/game_sa/CarEnterExit.cpp
source/game_sa/Events/EventKnockOffBike.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexLeaveBoat.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexLeaveCarAsPassengerWait.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexLeaveCarAsPassengerWait.h
source/game_sa/Tasks/TaskTypes/TaskSimpleCarJumpOut.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleCarSetPedInAsPassenger.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleCarSetPedInAsPassenger.h
source/game_sa/Tasks/TaskTypes/TaskSimpleCarSetPedOut.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleCarSetPedOut.h
source/toolsmenu/CDebugMenu.cpp

Also made it so that both `CTaskSimpleCarSetPedOut` and `CTaskSimpleCarSetPedInAsPassenger` take `eTargetDoor`, that's why there's a little bit more changes files.

`CTaskComplexLeaveCarAsPassengerWait`

---

source/game_sa/Tasks/TaskTypes/TaskSimpleSwim.cpp

Fix vortex entering bug

---

source/game_sa/Tasks/TaskManager.h
source/game_sa/Tasks/TaskTypes/TaskSimplePlayerOnFoot.cpp
source/game_sa/Tasks/TaskTypes/TaskSimplePlayerOnFoot.h

1. Reverted 0027c1eab09cf27299d74589a40eea3933bfbe63 (https://github.com/gta-reversed/gta-reversed-modern/pull/474))
2. All gotos are now gone. PR is tested.

CTaskSimplePlayerOnFoot refactor

---

source/game_sa/Clothes.cpp
source/game_sa/Clothes.h

Reverse class CClothes
<details><summary>Reversed functions</summary>
</details>

Reverse CClothes

---

source/game_sa/Pickup.cpp

Fix CPickup crash

---

source/InjectHooksMain.cpp
source/game_sa/Tasks/TaskTypes/Interior/TaskInteriorBeInHouse.cpp
source/game_sa/Tasks/TaskTypes/Interior/TaskInteriorBeInHouse.h

Game launches, haven't done any further testing.

`CTaskInteriorBeInHouse`

---

source/dllmain.cpp
source/game_sa/Animation/AnimManager.cpp
source/game_sa/Audio/managers/AESoundManager.cpp
source/game_sa/CdStreamInfo.cpp
source/game_sa/CustomCarPlateMgr.cpp
source/game_sa/Directory.cpp
source/game_sa/Entity/Ped/Ped.cpp
source/game_sa/Entity/Vehicle/Automobile.cpp
source/game_sa/Entity/Vehicle/Bike.cpp
source/game_sa/Events/EventHandler.cpp
source/game_sa/Garages.cpp
source/game_sa/Glass.cpp
source/game_sa/IKChain_c.cpp
source/game_sa/InterestingEvents.cpp
source/game_sa/OnscreenTimerEntry.cpp
source/game_sa/Pools.cpp
source/game_sa/PostEffects.cpp
source/game_sa/Scripts/TheScripts.cpp
source/game_sa/Streaming.cpp
source/game_sa/StuntJumpManager.cpp
source/game_sa/Tasks/Allocators/TaskAllocatorKillThreatsBasicRandomGroup.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleClimb.cpp
source/game_sa/World.cpp
source/game_sa/cTransmission.cpp

Replace all instances of `printf` with `DEV_LOG` in our code

Replace all `printf` with `DEV_LOG`

---

source/Base.h
source/game_sa/Collision/ColAccel.cpp
source/game_sa/Collision/ColModel.cpp
source/game_sa/Collision/ColModel.h
source/game_sa/Collision/ColPoint.h
source/game_sa/Collision/CollisionData.cpp
source/game_sa/Entity/Object/Object.cpp
source/game_sa/Entity/Vehicle/Automobile.cpp
source/game_sa/Entity/Vehicle/Automobile.h
source/game_sa/Entity/Vehicle/Bike.cpp
source/game_sa/Entity/Vehicle/Bike.h
source/game_sa/Entity/Vehicle/MonsterTruck.cpp
source/game_sa/Entity/Vehicle/Trailer.cpp
source/game_sa/Entity/Vehicle/Trailer.h
source/game_sa/Entity/Vehicle/Vehicle.cpp
source/game_sa/Entity/Vehicle/Vehicle.h
source/game_sa/Enums/eCarWheel.cpp
source/game_sa/Enums/eCarWheel.h
source/game_sa/FileLoader.cpp
source/game_sa/Models/VehicleModelInfo.h
source/reversiblehooks/ReversibleHooks.h

Tested, everything seems to work fine.
The code is mostly copy-pasted, with minor changes to classes that use extra supports (AKA suspension lines AKA lines).

`ProcessEntityCollision` shinanigans

---

source/InjectHooksMain.cpp
source/game_sa/Events/EventHandler.h
source/game_sa/PedIntelligence.h
source/game_sa/Tasks/TaskTypes/TaskComplexInvestigateDisturbance.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexInvestigateDisturbance.h
source/game_sa/common.h

Tried testing, but couldn't get the task to be constructed.
Let's merge it anyways.

`CTaskComplexInvestigateDisturbance`

---

source/game_sa/PathFind.h

Fix CMake build

---

source/game_sa/Core/Vector.cpp
source/game_sa/EntryExit.cpp
source/game_sa/EntryExit.h
source/game_sa/EntryExitManager.cpp
source/game_sa/PedGroup.cpp
source/game_sa/PedGroup.h
source/game_sa/Streaming.cpp
source/game_sa/Streaming.h
source/game_sa/Tasks/TaskTypes/TaskComplexFollowLeaderInFormation.h

I did fix these locally before #191 was merged, but I forgot to push the changes to the branch.

Fix `CEntryExitManager`/`CEntryExit` things

---

source/game_sa/Entity/Ped/Ped.cpp

Fix CPed::GrantAmmo

---

source/app/platform/win/VideoMode.cpp
source/app/platform/win/VideoModeSelectDialog.cpp
source/app/platform/win/WinMain.cpp
source/app/platform/win/WinPs.cpp
source/dllmain.cpp
source/extensions/Configs/WindowedMode.hpp
source/extensions/Configuration.hpp
source/game_sa/MenuManager.cpp

Adds 'WINDOWED' option to both in-game resolution option an device selection dialog.
Window is 640x480(?) by default but it can be stratched. (not rn because changing resolution locks the game) Game is still compatible with `III.VC.SA.WindowedMode.asi` so it's not big of a problem.

Windowed Mode

---

source/app/app_game.cpp
source/app/platform/win/Input.cpp
source/game_sa/MissionCleanup.cpp
source/game_sa/Scripts/TheScripts.cpp
source/game_sa/Scripts/TheScripts.h
source/game_sa/StuckCarCheck.cpp
source/game_sa/UpsideDownCarCheck.cpp

`CTheScripts::Process`

---

source/InjectHooksMain.cpp
source/game_sa/Camera.cpp
source/game_sa/Camera.h
source/game_sa/Core/Vector.h
source/game_sa/HandShaker.cpp
source/game_sa/HandShaker.h
source/toolsmenu/UIRenderer.cpp

Needs testing.
Appereatly this class is used for `AddShakeSimple` :
```cpp
// Test code
TheCamera.AddShakeSimple(100.f, 1, 100.f);
```

`CHandShaker`

---

source/game_sa/InterestingEvents.cpp
source/game_sa/InterestingEvents.h
source/game_sa/PedGroupMembership.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexChat.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexChat.h
source/game_sa/Tasks/TaskTypes/TaskSimpleChat.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleChat.h

Not really tested, but should work

`CTaskSimpleChat` and `CTaskComplexChat`

---

source/game_sa/FileLoader.cpp
source/game_sa/Game.cpp
source/game_sa/GangWars.cpp
source/game_sa/GangWars.h
source/game_sa/Radar.cpp
source/game_sa/Streaming.cpp
source/game_sa/TheZones.cpp
source/game_sa/TheZones.h
source/game_sa/Zone.h
source/game_sa/ZoneInfo.h
source/game_sa/common.h

Didn't test too much, but it seems to work

`CTheZones`

---

source/game_sa/C_PcSave.cpp

Fix C_PcSave::DeleteSlot return value

---

source/InjectHooksMain.cpp
source/game_sa/Animation/AnimBlendAssociation.h
source/game_sa/Tasks/TaskTypes/TaskSimpleCarAlign.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleCarCloseDoorFromInside.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleCarCloseDoorFromOutside.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleCarGetIn.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleCarGetOut.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleCarJumpOut.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleCarOpenDoorFromOutside.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleCarOpenLockedDoorFromOutside.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleCarOpenLockedDoorFromOutside.h
source/game_sa/Tasks/TaskTypes/TaskSimpleCarShuffle.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleCarShuffle.h
source/game_sa/Tasks/TaskTypes/TaskSimpleCarSlowDragPedOut.cpp
source/game_sa/Tasks/TaskTypes/TaskSimplePickUpBike.cpp
source/game_sa/VehicleAnimGroupData.cpp
source/game_sa/VehicleAnimGroupData.h

`CTaskSimpleCarShuffle`

---

source/game_sa/Collision/CollisionData.cpp
source/game_sa/Events/EventDamage.h
source/game_sa/Tasks/TaskTypes/TaskSimpleThrowProjectile.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleThrowProjectile.h

I'm not sure if `StartAnim` is correct, it might be playing the wrong throw animation, not sure.
Other than that, it's fine [and the before mentioned issue can be fixed later]

`CTaskSimpleThrowProjectile`

---

source/game_sa/PathFind.cpp
source/game_sa/PathFind.h

Use defined NUM_TOTAL_PATH_NODE_AREAS instead calculating it many times

---

source/extensions/WEnum.hpp
source/game_sa/Enums/eDirection.h
source/game_sa/Tasks/TaskTypes/TaskComplexHitByGunResponse.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexHitByGunResponse.h
source/game_sa/Tasks/TaskTypes/TaskComplexHitResponse.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexHitResponse.h

Untested, but the 2 classes combined are like 10 lines each (/wo boilerplate code ofc)

`CTaskComplexHitResponse`, `CTaskComplexHitByGunResponse`

---

source/game_sa/Animation/AnimBlendFrameData.h
source/game_sa/Entity/Physical.h
source/game_sa/Messages.cpp
source/game_sa/Pickups.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleJetPack.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleJetPack.h
source/toolsmenu/UIRenderer.cpp

`CTaskSimpleJetPack`

---

source/game_sa/PathFind.cpp

Something's wrong with this function.
I specifically reversed `CTaskComplexFollowNodeRoute` to figure out what the problem is, but no avail.
Will just disable it for now....

Disable `DoPathSearch`

---

source/InjectHooksMain.cpp
source/game_sa/Tasks/TaskTypes/Interior/TaskInteriorSitAtDesk.cpp
source/game_sa/Tasks/TaskTypes/Interior/TaskInteriorSitAtDesk.h

Check the code pls, should be good tho

`CTaskInteriorSitAtDesk`

---

source/InjectHooksMain.cpp
source/extensions/EntityRef.hpp
source/game_sa/Collision/CollisionEventScanner.h
source/game_sa/Entity/Ped/Ped.h
source/game_sa/PathFind.cpp
source/game_sa/PedIntelligence.h
source/game_sa/Tasks/TaskComplexSequence.cpp
source/game_sa/Tasks/TaskManager.h
source/game_sa/Tasks/TaskTypes/SeekEntity/PosCalculators/EntitySeekPosCalculatorXYOffset.h
source/game_sa/Tasks/TaskTypes/SeekEntity/TaskComplexSeekEntity.h
source/game_sa/Tasks/TaskTypes/SeekEntity/TaskComplexSeekEntityXYOffset.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexFollowNodeRoute.h
source/game_sa/Tasks/TaskTypes/TaskComplexGoToPointAndStandStill.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexGoToPointAndStandStill.h
source/game_sa/Tasks/TaskTypes/TaskComplexGoToPointAndStandStillTimed.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexWalkAlongsidePed.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexWalkAlongsidePed.h
source/game_sa/Tasks/TaskTypes/TaskSimpleGoTo.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleGoTo.h
source/game_sa/Tasks/TaskTypes/TaskSimpleGoToPoint.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleGoToPoint.h
source/reversiblehooks/ReversibleHook/Virtual.h
source/reversiblehooks/ReversibleHooks.cpp
source/reversiblehooks/ReversibleHooks.h
source/toolsmenu/UIRenderer.cpp

I went insane.
`SeekEntity` stuff just can't be unhooked (*game crashes*) cause fuck knows
turns out `seekInterval` and `scanInterval` were swapped :D (And constructors can't be unhooked, so yeah, that was fun)
works like OG
Check out 0b99ad064d937076a5cc3ff8a32e50c106503a72

`CTaskComplexWalkAlongsidePed`

---

source/InjectHooksMain.cpp
source/game_sa/Tasks/TaskTypes/Interior/TaskInteriorGoToInfo.cpp
source/game_sa/Tasks/TaskTypes/Interior/TaskInteriorGoToInfo.h
source/game_sa/Tasks/TaskTypes/TaskComplexFollowNodeRoute.h

Not tested, but code checks out

`CTaskInteriorGoToInfo`

---

source/game_sa/Tasks/TaskTypes/TaskComplexEnterCar.cpp

Needs testing, but I think that's it.
(Fixes #656)

Fix `CTaskComplexEnterCar::CreateFirstSubTask`

---

source/InjectHooksMain.cpp
source/game_sa/Core/List_c.h
source/game_sa/Interior/InteriorGroup_c.cpp
source/game_sa/Interior/InteriorGroup_c.h
source/game_sa/Interior/InteriorManager_c.cpp
source/game_sa/Interior/InteriorManager_c.h
source/game_sa/PathFind.cpp
source/game_sa/Tasks/TaskTypes/Interior/TaskInteriorBeInHouse.cpp
source/game_sa/Tasks/TaskTypes/Interior/TaskInteriorBeInHouse.h
source/game_sa/Tasks/TaskTypes/Interior/TaskInteriorShopKeeper.cpp
source/game_sa/Tasks/TaskTypes/Interior/TaskInteriorShopKeeper.h
source/game_sa/Tasks/TaskTypes/Interior/TaskInteriorUseInfo.h

Not even sure where to test this
I guess I have to enter an interior somewhere with a shopkeeper?
Not sure where tho.
EDIT:
- There's a bug with `CPathFind` when entering interiors. Not yet sure what causes it, but disabling all hooks of it before entering the interior fixes it.
- Peds inside interiors are just a ball (No animation applied, or something's wrong with the anims. Note that I tested this before merging #655)

`CTaskInteriorShopKeeper`

---

source/InjectHooksMain.cpp
source/game_sa/Entity/Vehicle/Vehicle.h
source/game_sa/Tasks/TaskTypes/TaskComplexDiveFromAttachedEntityAndGetUp.h
source/game_sa/Tasks/TaskTypes/TaskComplexEvasiveDiveAndGetUp.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexEvasiveDiveAndGetUp.h
source/game_sa/Tasks/TaskTypes/TaskSimpleEvasiveDive.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleEvasiveDive.h

Needs testing, though code so short it must be fine

`CTaskComplexEvasiveDiveAndGetUp`

---

source/game_sa/Events/EventSexyPed.cpp

Finish `CEventSexyPed::AffectsPed`

`CEventSexyPed`

---

source/InjectHooksMain.cpp
source/game_sa/Entity/Vehicle/Vehicle.h
source/game_sa/Events/EventHandler.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexHitPedWithCar.h
source/game_sa/Tasks/TaskTypes/TaskSimpleHurtPedWithCar.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleHurtPedWithCar.h

`CTaskSimpleHurtPedWithCar`

---

source/InjectHooksMain.cpp
source/game_sa/Events/EventHandler.cpp
source/game_sa/Tasks/Task.h
source/game_sa/Tasks/TaskTypes/TaskComplexFacial.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexFacial.h
source/game_sa/Tasks/TaskTypes/TaskSimpleFacial.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleFacial.h
source/game_sa/Tasks/TaskTypes/TaskSimplePause.cpp
source/game_sa/Tasks/TaskTypes/TaskSimplePause.h

Didn't test in-depth, but should be good

`CTaskComplexFacial`, `CTaskSimpleFacial`

---

source/game_sa/SpecialFX.cpp

Even though it's an unused function, it still needs to be reversed.

Update AddWeaponStreak, SpecialFX.cpp

---

source/app/platform/win/WinMain.cpp

Fix newGameFirstTime initialization

---

source/game_sa/Animation/AnimBlendNode.cpp

Fix https://github.com/gta-reversed/gta-reversed-modern/issues/709

Fix `CAnimBlendNode::FindKeyFrame` (#709)

---

source/game_sa/PedGroup.cpp

Fixes #712
@Pirulax : please merge after you check the code thoroughly.

CPedGroup::Teleport: add the forgotten leader check

---

source/game_sa/Coronas.cpp
source/game_sa/Sprite.cpp

BEFORE
> https://github.com/gta-reversed/gta-reversed-modern/assets/70571714/6b459ac9-1fb0-42b8-a7dc-5b0277d8fade
AFTER
> https://github.com/gta-reversed/gta-reversed-modern/assets/70571714/e7e29930-d541-4b55-bfd3-3000429d0a50

Fix sun flares flickering and size

---

source/game_sa/CarEnterExit.cpp

This bug
https://github.com/gta-reversed/gta-reversed-modern/assets/70571714/472ae11e-c004-471d-bad7-56fd89c0499c

Correcting the position of the hands in the car

---

source/game_sa/PathFind.cpp
source/game_sa/TheZones.cpp

Without a fix:
https://github.com/gta-reversed/gta-reversed-modern/assets/70571714/7e786757-7a78-4b5a-84f9-b5f162b5e99c

Fix cops path and car models selection

---

source/extensions/WEnum.hpp
source/game_sa/3dMarkers.cpp
source/game_sa/3dMarkers.h
source/game_sa/Checkpoint.cpp
source/game_sa/Checkpoint.h
source/game_sa/Checkpoints.cpp
source/game_sa/Checkpoints.h
source/game_sa/Clock.cpp
source/game_sa/Core/Vector.h
source/game_sa/Core/Vector2D.h
source/game_sa/SpecialFX.cpp
source/game_sa/SpecialFX.h
source/game_sa/WaterLevel.h
source/toolsmenu/DebugModules/CheckpointsDebugModule.cpp
source/toolsmenu/DebugModules/CheckpointsDebugModule.hpp
source/toolsmenu/DebugModules/DebugModules.cpp

`CCheckpoint` and `CCheckpoints`

---

source/extensions/FixedFloat.hpp
source/game_sa/Animation/AnimBlendAssocGroup.cpp
source/game_sa/Animation/AnimBlendAssocGroup.h
source/game_sa/Animation/AnimBlendHierarchy.h
source/game_sa/Animation/AnimBlendSequence.cpp
source/game_sa/Animation/AnimBlendStaticAssociation.cpp
source/game_sa/Animation/AnimBlendStaticAssociation.h
source/game_sa/Animation/AnimManager.cpp
source/game_sa/Animation/AnimManager.h
source/game_sa/Animation/AnimSequenceFrames.h
source/game_sa/CutsceneMgr.cpp
source/game_sa/Enums/AnimationEnums.h
source/game_sa/Fx/FxManager.cpp
source/game_sa/Plugins/RpAnimBlendPlugin/RpAnimBlend.cpp
source/game_sa/Scripts/Commands/Character.cpp

Though, doesn't manage to fix #731 :(
1. Fixes a few bugs I made.
2. Also there are minor refactors.
3. Add basic arithmetic ops support to `FixedFloat` that's done between 2 `FixedFloat`s (This was done to fix the bug in `CalcTotalTime`)

Fix (NOTSA) Animation code bugs

---

source/app/platform/win/WinMain.cpp
source/game_sa/Coronas.cpp
source/game_sa/PlantMgr.cpp
source/game_sa/PlantMgr.h

Fixed 2 bugs, now the game exits without crashing when closed.
Also did some minor refactors while on the way.

Fix crashes 

---

source/InjectHooksMain.cpp
source/game_sa/Collision/ColModel.cpp
source/game_sa/Collision/ColSphere.h
source/game_sa/Collision/TempColModels.cpp
source/game_sa/Collision/TempColModels.h
source/game_sa/Entity/Ped/Ped.h
source/game_sa/Entity/Vehicle/Bike.cpp
source/game_sa/Entity/Vehicle/Vehicle.h
source/game_sa/FileLoader.cpp

`CTempColModels`

---

source/game_sa/Audio/hardware/AEAudioHardware.cpp
source/game_sa/Entity/Object/CutsceneObject.cpp
source/game_sa/Entity/Ped/Ped.cpp
source/game_sa/Entity/Ped/Ped.h
source/game_sa/Entity/Ped/PlayerPed.cpp
source/game_sa/Events/EventDamage.cpp
source/game_sa/IKChain_c.cpp
source/game_sa/PedIntelligence.cpp
source/game_sa/RenderWare/rw/rphanim.cpp
source/game_sa/RenderWare/rw/rphanim.h
source/game_sa/Tasks/TaskTypes/TaskComplexMedicTreatInjuredPed.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexMedicTreatInjuredPed.h
source/game_sa/Tasks/TaskTypes/TaskComplexTreatAccident.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleArrestPed.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleThrowProjectile.cpp

Didn't test in detail, but game doesn't crash....

Fix `CPed::GetBonePosition` + Sanity checks

---

source/game_sa/Core/Matrix.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexEnterCar.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleUseGun.cpp
source/game_sa/Weapon.cpp

Tested, but perhaps some more testing wouldn't be a bad idea...

`CWeapon:SetUpPelletCol` + Fix a few bugs

---

README.md

```cpp
decltype(auto) Get(this auto&& self) noexcept { return self.m_Ptr; }
auto&& GetModelDummyPosition(this auto&& self, eVehicleDummy dummy) { return self.m_pVehicleStruct->m_avDummyPos[dummy]; } // NOTSA
```
"this auto&& self" - supported in compiler versions starting from c++23

Edit README: Now requires c++23

---

README.md

Improve docs: 
- Add Discord link
- Remove CMake build instructions [as builds produced by it don't work]
- Some minor wording changes

Improve docs: Add Discord link, remove CMake build instructions

---

source/game_sa/Scripts/Commands/Text.cpp

Fix COMMAND_DISPLAY_TEXT

---

source/game_sa/StuntJumpManager.cpp

Reset from a successful stunt jump properly

---

source/game_sa/Cam.cpp
source/game_sa/Cam.h
source/game_sa/Camera.cpp
source/game_sa/Camera.h
source/game_sa/Scripts/Commands/Camera.cpp

Fix  CCamera::ProcessFade() Incorrect behavior when fading out (Fixes #789)

---

source/game_sa/Cam.cpp
source/game_sa/Camera.cpp

tested https://discord.com/channels/479682870047408139/1327783261853843547

CCamera::Find3rdPersonCamTargetVector

---

.github/workflows/build.yml
source/game_sa/Crime.cpp

Final test to CCrime::ReportCrime
```
if ((CLocalisation::GermanGame() && notsa::contains({CRIME_DAMAGE_CAR, CRIME_DAMAGE_COP_CAR, CRIME_SET_PED_ON_FIRE, CRIME_SET_COP_PED_ON_FIRE}, crimeType))
|| CWanted::WorkOutPolicePresence(comittedByPos, FindImmediateDetectionRange(crimeType))) {
```

[TESTED] Fixed german logic in CCrime::ReportCrime

---

source/game_sa/Audio/AudioEngine.cpp
source/game_sa/Audio/AudioEngine.h
source/game_sa/Audio/entities/AECollisionAudioEntity.cpp
source/game_sa/Audio/entities/AECollisionAudioEntity.h
source/game_sa/Entity/Physical.cpp
source/game_sa/Entity/Physical.h
source/game_sa/Entity/Vehicle/Vehicle.cpp
source/game_sa/Entity/Vehicle/Vehicle.h

Fixes #891
Issue was that `CColData` wasn't properly initialized (Number of spheres was set to 1, but the pointer wasn't set).
Another issue was the pointer not being correct.
Also, there was some other issue with `DoBladeCollision` that prevented the blades from spinning... So now helicopters work as they should.

Fix `DoBladeCollision`

---

README.md

Fixes build status ( supposedly )

Fix `Build Status`

---

source/game_sa/Scripts/Commands/Basic.cpp
source/game_sa/Scripts/Commands/Camera.cpp
source/game_sa/Scripts/Commands/Character.cpp
source/game_sa/Scripts/Commands/Clock.cpp
source/game_sa/Scripts/Commands/Comparasion.cpp
source/game_sa/Scripts/Commands/Game.cpp
source/game_sa/Scripts/Commands/Generic.cpp
source/game_sa/Scripts/Commands/Math.cpp
source/game_sa/Scripts/Commands/Mission.cpp
source/game_sa/Scripts/Commands/Object.cpp
source/game_sa/Scripts/Commands/Pad.cpp
source/game_sa/Scripts/Commands/Ped.cpp
source/game_sa/Scripts/Commands/Player.cpp
source/game_sa/Scripts/Commands/Script.cpp
source/game_sa/Scripts/Commands/Sequence.cpp
source/game_sa/Scripts/Commands/Text.cpp
source/game_sa/Scripts/Commands/Unused.cpp
source/game_sa/Scripts/Commands/Utility.cpp
source/game_sa/Scripts/Commands/Vehicle.cpp

I did this thinking it might speed up the compilation, but no success...
Wrapping functions into anonymous namespaces will restrict them to the TU (.cpp file) they're in, so, no linker symbol has to be generated for them

Wrap script commands into anonymous namespaces (Hide functions from the linker)

---

source/game_sa/Entity/Physical.cpp
source/game_sa/Events/EventHandler.cpp
source/game_sa/Events/EventSoundQuiet.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexJump.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleClimb.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleClimb.h
source/game_sa/Tasks/TaskTypes/TaskSimpleInAir.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleInAir.h
source/game_sa/Tasks/TaskTypes/TaskSimpleJump.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleJump.h
source/game_sa/Tasks/TaskTypes/TaskSimpleSwim.h

Tested, climbing works as expected.

Finish up and refactor `CTaskSimpleClimb` 

---

source/game_sa/Animation/AnimBlendAssociation.h
source/game_sa/IKChainManager_c.cpp
source/game_sa/Population.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexFacial.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexJump.cpp

Fix cast crashes

---

source/game_sa/Audio/loaders/AEBankLoader.h
source/game_sa/Audio/loaders/AEMP3BankLoader.cpp

Fix `CAEMP3BankLoader::LoadSoundBank` and `LoadSound`

---

source/game_sa/Entity/Vehicle/Bmx.cpp
source/game_sa/Entity/Vehicle/QuadBike.cpp
source/game_sa/RideAnimData.h

implemented CBmx::ProcessControl, CBmx::ProcessBunnyHop, CBmx::LaunchBunnyHopCB
renamed CRideAnimData.dword10 -> CRideAnimData.m_fLeanFwd

CBmx improvements, [Tested]

---

CMakeLists.txt
conanfile.py
source/CMakeLists.txt
source/game_sa/MenuManager.h
source/game_sa/Plugins/JPegCompressPlugin/JPegCompress.cpp
source/game_sa/Plugins/JPegCompressPlugin/JPegCompress.h
source/game_sa/RenderWare/rw/rwcore.cpp

JPegCompress plugin

---

source/game_sa/Scripts/Commands/Commands.hpp
source/game_sa/Scripts/Commands/Game.cpp
source/game_sa/Scripts/Commands/Stat.cpp
source/game_sa/Scripts/RunningScript.cpp

Didn't test indepth, but should work all good
Game launches just fine, `GetStat` is called, no crash.

Stat script commands

---

source/game_sa/Entity/Vehicle/Automobile.cpp
source/game_sa/Entity/Vehicle/Automobile.h

This seems to have fixed the issue.

Zero init `CAutomobile::m_apWheelCollisionEntity`

---

source/game_sa/Entity/Entity.cpp
source/game_sa/Pipelines/CustomBuilding/CustomBuildingDNPipeline.cpp
source/game_sa/Pipelines/CustomBuilding/CustomBuildingDNPipeline.h

Fix crash caused by misinterpreted type

---

source/game_sa/Audio/entities/AEWeaponAudioEntity.cpp

Fix `CAEWeaponAudioEntity::UpdateParameters`

---

source/game_sa/Audio/AESound.cpp
source/game_sa/Audio/AESound.h
source/game_sa/Audio/managers/AESoundManager.cpp
source/game_sa/Audio/managers/AESoundManager.h

Fix sounds

---

source/game_sa/Events/EventHandler.cpp
source/game_sa/PedIntelligence.h
source/game_sa/PedStuckChecker.h
source/game_sa/Tasks/TaskTypes/TaskComplexClimb.h
source/game_sa/Tasks/TaskTypes/TaskComplexJump.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexJump.h
source/game_sa/Tasks/TaskTypes/TaskComplexMoveBackAndJump.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexStuckInAir.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexStuckInAir.h
source/game_sa/Tasks/TaskTypes/TaskSimpleFall.h
source/game_sa/Tasks/TaskTypes/TaskSimplePlayerOnFoot.cpp

Can't really test because I have no clue how to trigger it.
Maybe will figure it out once we reverse `CPedStuckChecker::TestPedStuck`

`CTaskComplexStuckInAir`

---

source/game_sa/PathFind.cpp
source/game_sa/Scripts/Commands/ScriptCommands.cpp
source/game_sa/Scripts/Commands/VehicleCommands.cpp
source/game_sa/StuckCarCheck.cpp
source/game_sa/StuckCarCheck.h

I'm a bit newbie in C++, especially modern, don't judge too hard.

reverse CStuckCheck

---

source/app/platform/SDLWrapper.cpp
source/game_sa/Frontend/MenuManager_Draw.cpp

Not the best fix, but should work for now...

Fix mouse in menu

---

source/game_sa/Frontend/MenuManager_Input.cpp
source/game_sa/Pad.h

Fix for sensitivity, etc not working with left/right keys properly.

Fix menu slider

---

source/game_sa/Darkel.cpp

kill stats are updated regardless of frenzy status
tested

fix RegisterKillByPlayer

---

source/game_sa/Scripts/TheScripts.cpp

Fixes newly added assert in `SetCurrentIP`

Don't set IP to nullptr in `StartNewScript`

---

source/game_sa/Pipelines/CustomBuilding/CustomBuildingPipeline.cpp
source/game_sa/Pipelines/CustomBuilding/CustomBuildingPipeline.h
source/game_sa/Pipelines/CustomCarEnvMap/CustomCarEnvMapPipeline.cpp
source/game_sa/Pipelines/CustomCarEnvMap/CustomCarEnvMapPipeline.h
source/game_sa/RenderWare/rw/rpmatfx.h

No clue how to test, because I have no clue what uses it.... :D
Edit: seems like something in SF triggers it

`CCustomBuildingPipeline`

---

source/game_sa/Entity/Ped/PlayerPed.cpp
source/game_sa/Weapon.cpp
source/game_sa/Weapon.h

lock-on/auto-aim works now on peds and objects.

Fix autoaim

---

source/game_sa/Entity/Vehicle/Automobile.cpp
source/game_sa/FileLoader.cpp

Fix skimmer bug, [see](https://github.com/CookiePLMonster/SilentPatch/commit/881aded7237067202025934796cc2313104cba8c#diff-dced484b9e5c91f46368608ae464c11e6f83915e899f55e3ba23c33440858df2)
Fixes #922

Fix skimmer bug

---

source/CMakeLists.txt
source/InjectHooksMain.cpp
source/game_sa/Audio/AudioEngine.cpp
source/game_sa/Audio/AudioEngine.h
source/game_sa/Conversations.cpp
source/game_sa/Conversations.h
source/game_sa/Conversations/ConversationForPed.cpp
source/game_sa/Conversations/ConversationForPed.h
source/game_sa/Conversations/ConversationNode.cpp
source/game_sa/Conversations/ConversationNode.h
source/game_sa/Conversations/Conversations.cpp
source/game_sa/Conversations/Conversations.h
source/game_sa/Conversations/PedToPlayerConversations.cpp
source/game_sa/Conversations/PedToPlayerConversations.h
source/game_sa/Scripts/Commands/Commands.hpp
source/game_sa/Scripts/Commands/ConversationCommands.cpp
source/game_sa/Scripts/Commands/ScriptCommands.cpp
source/game_sa/Scripts/RunningScript.cpp
source/game_sa/common.cpp
source/game_sa/common.h

basic stuff, early feedback is appreciated

Reversing Conversation commands

---

source/game_sa/Scripts/CommandParser/ReadArg.hpp
source/game_sa/Scripts/Commands/PlayerCommands.cpp
source/game_sa/Scripts/Commands/VehicleCommands.cpp

Remaining player commands

---

source/app/app_debug.h
source/toolsmenu/DebugModules/HooksDebugModule.cpp

Add menu bar to hooks tool to export `hooks.csv` from in-game

Add `hooks.csv` export

---

source/InjectHooksMain.cpp
source/extensions/utility.hpp
source/game_sa/Clock.h
source/game_sa/Collision/Box.cpp
source/game_sa/Collision/Box.h
source/game_sa/Collision/ColourSet.cpp
source/game_sa/Collision/ColourSet.h
source/game_sa/Shadows.cpp
source/game_sa/Shadows.h
source/game_sa/TimeCycle.cpp
source/game_sa/TimeCycle.h
source/toolsmenu/DebugModules/TimeCycleDebugModule.cpp
source/toolsmenu/DebugModules/TimeCycleDebugModule.h

`CalcColoursForPoint` not tested all that much, but seems to be ok

`CTimeCycle`
