source/PluginBase.h
source/game_sa/Acquaintance.cpp
source/game_sa/Audio/entities/AEPedSpeechAudioEntity.cpp
source/game_sa/Audio/entities/AEVehicleAudioEntity.cpp
source/game_sa/Audio/hardware/AEAudioHardware.cpp
source/game_sa/Audio/hardware/AEStreamingChannel.cpp
source/game_sa/BreakObject_c.cpp
source/game_sa/IKChainManager_c.cpp
source/game_sa/PedClothesDesc.cpp
source/game_sa/ProjectileInfo.cpp
source/game_sa/ProjectileInfo.h
source/game_sa/Scripts/RunningScript.cpp
source/game_sa/UpsideDownCarCheck.cpp

So there was a little issue we have had, which lead to this.
This way `CallMethod` can't be called with incorrect first argument.

Add constrains to plugin::CallMathod (And bad calls)

---

source/game_sa/Streaming.cpp

The `next` value from the node has to be saved because when the entity it belongs to is removed it's invalidated as well.

Fix CStreaming list iters

---

source/game_sa/Font.cpp

Fixes this (Notice how it has no namespace):

Fix missing namespace for GetLetterIdPropValue

---

source/game_sa/GameLogic.h
source/game_sa/Plugins/CollisionPlugin/CollisionPlugin.cpp
source/game_sa/Plugins/CollisionPlugin/CollisionPlugin.h
source/game_sa/Plugins/NodeNamePlugin/NodeName.cpp
source/game_sa/Plugins/NodeNamePlugin/NodeName.h
source/game_sa/Plugins/PipelinePlugin/PipelinePlugin.cpp
source/game_sa/Plugins/PipelinePlugin/PipelinePlugin.h

1. eGameState was incorrectly read from memory as int, which causes various small issues like markers not working sometimes
2. RW Plugins work with reversible hooks now, greatly improving stability for unhooking/rehooking stuff

Improve reversible hooks stability, fix static field size issue

---

source/game_sa/Clock.cpp

`ms_nGameClockMonth` is in range [1:12], and we need to use it to index array with 12 elements

Fix sneaky array out of bounds access bug in CClock

---

source/reversiblehooks/ReversibleHook/Simple.h
source/toolsmenu/DebugModules/HooksDebugModule.cpp

Middle and right mouse buttons can be used to copy them individually. 
The pic has the addresses swapped up, and `0x` prefix missing, but those have been corrected since.

Make copying function addresses from hook tool possible

---

source/app/platform/win/win_impl.cpp

* Fixes fullscreen screenshots in windowed mode. (in vanilla SA it's probably the ASI's fault.)
* Fixes capture of whole window instead of the client (i.e. the game area) area. (first image is vanilla, second is this PR)
<details>
<summary>Images</summary>
</details>

Fix psGrabScreen

---

source/game_sa/C_PcSave.cpp
source/game_sa/GenericGameStorage.cpp
source/game_sa/Tasks/TaskTypes/TaskComplexTurnToFaceEntityOrCoord.cpp
source/reversiblehooks/ReversibleHooks.h

Adds `reversed` option to `HookOptions`, should be used for functions that aren't yet reversed, same as the old `{ .enabled = false, .locked = true }`.
TODO [Separate PR]: Uncomment all commented out hooks and add use `{ .reversed = false }` - Do this in multiple batches, so in case it starts crashing bisect can be used.

HookOptions: Add `reversed`

---

source/game_sa/Tasks/TaskTypes/TaskSimpleCarWaitToSlowDown.cpp
source/game_sa/Tasks/TaskTypes/TaskSimpleRunNamedAnim.cpp

fixes #353, couldn't get it to crash on task allocation as in issue report, but player was teleported way out of map bounds, which most likely caused tasks to go crazy

Fix invalid position transformation in CTaskSimpleRunNamedAnim

---

source/game_sa/Tasks/TaskTypes/TaskSimpleHoldEntity.cpp

The crash was probably introduced during refactor. Tested fix.

Fix CTaskSimpleHoldEntity::StartAnim crash

---

source/game_sa/PopCycle.cpp
source/game_sa/PopCycle.h

In the vanilla game the %'s in `m_nPercTypeGroup` array add up to 100% (The original code rescales the values in order to make sure this is the case...but fails sometimes due to rounding errors)
But we take another route and don't normalize to 100%. This way there's no rounding error involved and everything works perfectly. 
They probably went for `100%` sum for optimization purposes (to avoid having to `accumulate` like we do now), but we don't need that, we just need bug free code.

PopCycle; Fix group percs bug

---

source/toolsmenu/DebugModules/HooksDebugModule.cpp
source/toolsmenu/DebugModules/HooksDebugModule.h
source/toolsmenu/UIRenderer.cpp

A little feature that allows changing hook state just by sliding the mouse cursor over it while holding a button.
Controls:
- Right click held + Slide = Set all hooks to the same state as the one over which the mouse was when the right click was pressed
- Middle button held + Slide = Toggle all hooks - Kinda buggy if you slide it too fast, i recommend using the right click version
That's about it. I just found it useful when trying to hunt down a bug and had to manually reactivate a lot of hooks. Bonus is that when holding the right mouse button you can still scroll.

HooksDebug: SliderSetter

---

source/game_sa/Collision/ColHelpers.h
source/game_sa/Collision/ColTriangle.h
source/game_sa/Collision/CollisionData.h
source/game_sa/Plant/PlantLocTri.cpp
source/game_sa/Plant/PlantLocTri.h

Collision (4CC "COLL") crashed the game (Seems like very rarely do models have this version used, but some RC vehicle did, so I crashed)
Fix was pretty easy, there was a bad cast `*reinterpret_cast<tColLighting*>(nLigthing)`, now I've removed the casts completely, that's why there's a little more changes than expected.

Fix Col V0 crashing game (Caused by incorrect cast)

---

.clang-format

I've made this file using a [site](https://clang-format-configurator.site).
Command to run (after editing `.clang-format`):
`git add .clang-format && git checkout . && find ./source/ -iname *.h -o -iname *.cpp | xargs clang-format -i`
Command to run (to just run `clang-format`):
`find ./source/ -iname *.h -o -iname *.cpp | xargs clang-format -i`

Add `.clang-format`

---

source/game_sa/Collision/Collision.cpp

Also, I'm trying to figure out if the nans we get everywhere are related to `CCollision` code.

Disable CCollision hooks for better performance

---

source/game_sa/Tasks/TaskTypes/TaskComplexUseEffect.cpp

Fixes a crash that occurs when entering the Woozie's casino

Fix CTaskComplexUseEffect copy constructor

---

source/game_sa/Fx/FxEmitter.cpp
source/game_sa/Maths.cpp
source/game_sa/Maths.h
source/game_sa/WaterLevel.cpp
source/game_sa/WaterLevel.h

- Fixes: #533 
- Fixes waves being slightly different from original ones (`faWaveMultipliersX` used by accident instead of `faWaveMultipliersY`), also cleanups to that method
- Fixes `SplitWaterRectangleAlongXLine` and `SplitWaterRectangleAlongYLine` using wrong indices
- Fixes water quads loading incorrectly. It's a hack fix, but results in every single vertice being sorted correctly. I think that the generic solution that was implemented earlier is not the correct fit for this use case, and we should revert back to the original SA logic.
With my changes all quads load correctly, and all but one triangle is loaded correctly. The one remaining incorrect triangle can be found in SF docks:

Fix few water related issues

---

source/app/platform/win/WndProc.cpp

Fixes shift keys not being properly handled by the game.
I'm not sure what is wrong with the original code, but I find the unrolled code much more readable - and it works
Fixes #814

Fix shift keys not being registered

---

source/app/platform/win/WinPs.cpp

GTA San Andreas will not work with DPI other than 100, this is because some newer versions of Windows assign the resolution based on the DPI.

Fix for hard DPI bug Windows 10+

---

.github/workflows/build.yml

Previous image is quite old, and also, this resolves an [issue](https://github.com/libsdl-org/SDL/issues/11487) that we'd have with SDL3

CI: Use `windows-2025` image [Instead of `windows-2022`]

---

CMakeLists.txt
source/CMakeLists.txt

`/SAFESH` is not necessary (We didn't have it with premake either)
`/ZI` was not added for some reason (I think because `add_compile_options` doesn't need a target, but only options)

Fix Edit&Continue

---

source/game_sa/Audio/AEAudioEnvironment.cpp
source/game_sa/Audio/AESound.cpp
source/game_sa/Core/Matrix.h
source/game_sa/Tasks/TaskTypes/TaskComplexRoadRage.cpp

The abovementioned function was buggy, and caused the sound to be a almost silent in one ear and loud in the other.
Issue was my assumption of `InverseTransformVector({-p.x, p.y, p.z})` being the same as just negating the resulting `x`.
All other changes are mostly cosmetic/make the code be more OG.

Fix `CAEAudioEnvironment::GetPositionRelativeToCamera`

---

source/toolsmenu/DebugModules/CStreamingDebugModule.cpp

Small fix for a restart crash.
When running the game after opening up the streaming debug menu, ImGui restores the window visible.
This causes DrawListSizes to run and crash the game due to begin/end inside of GetListSize being null.

ImGui DrawListSizes Crash Fix

---

source/game_sa/Scripts/RunningScript.h
source/game_sa/Scripts/TheScripts.cpp

tested, no more asserts when picking up the phone when Sweet calls

Fix seemingly out-of-bounds read of `m_LocalVars` in `CRunningScript`

---

source/game_sa/Core/Vector.h
source/game_sa/Core/Vector2D.h

MSVC `14.44.35207` (VS `17.14.2`) moment:
```shell
..\source\game_sa\Core\Vector2D.h(188,29): error C2216: "friend" cannot be used with "static"
..\source\game_sa\Core\Vector2D.h(192,29): error C2216: "friend" cannot be used with "static"
..\source\game_sa\Core\Vector.h(179,27): error C2216: "friend" cannot be used with "static"
..\source\game_sa\Core\Vector.h(183,27): error C2216: "friend" cannot be used with "static"
```
What exactly to fix it to I don't know, I think `constexpr` will do.

Fix Build MSVC > `14.44.X` (VS `17.14.X`)

---

source/app/app_game.cpp
source/game_sa/Cam.cpp
source/game_sa/Collision/ColourSet.cpp
source/game_sa/Collision/ColourSet.h
source/game_sa/Entity/Ped/Ped.cpp
source/game_sa/Game.cpp
source/game_sa/PostEffects.cpp
source/game_sa/Shadows.cpp
source/game_sa/TimeCycle.cpp
source/game_sa/TimeCycle.h
source/toolsmenu/DebugModules/TimeCycleDebugModule.cpp
source/toolsmenu/DebugModules/TimeCycleDebugModule.h

1. Remove conversions where not required.
2. Reverse `CTimeCycle::Initialise` and slightly refactor `CTimeCycle::CalcColoursForPoint`
3. Implementation of `eTimeType`
4. Sort variables in `CTimeCycle` in descending order by address
5. Set negative values for Float values (why it was necessary to remove the negative sign is a question).
6. Fix `PostFx` in Debug

Fix types and color in `CColourSet` and `CTimeCycle`
